# Generated by Django 4.2.4 on 2023-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
