# Generated by Django 4.2.4 on 2023-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=2000),
        ),
    ]
