# Generated by Django 4.2.4 on 2023-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_userquestiondata_question_user_question_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestiondata',
            name='tag',
            field=models.CharField(choices=[('READ', 'Lida'), ('UNREAD', 'Não lida'), ('IMPORTANT', 'Importante'), ('OK', 'OK'), ('STUDY', 'Estudar')], default='UNREAD', max_length=10, null=True),
        ),
    ]
