# Generated by Django 4.2.4 on 2023-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_userquestiondata_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestiondata',
            name='tag',
            field=models.CharField(choices=[('READ', 'Lida'), ('UNREAD', 'Não lida'), ('IMPORTANT', 'Importante'), ('OK', 'OK'), ('STUDY', 'Estudar')], default='READ', max_length=10, null=True),
        ),
    ]
